def load_test_data
  @chef_1 = Chef.create!(name: "Anna")
  @chef_2 = Chef.create!(name: "Justin")
  @chef_3 = Chef.create!(name: "Luca")
  @dish_1 = @chef_1.dishes.create!(name: "salad", description: "This is a salad.")
  @dish_2 = @chef_1.dishes.create!(name: "wings", description: "These are wings.")
  @dish_3 = @chef_1.dishes.create!(name: "pizza", description: "This is a pizza.")
  @ingredient_1 = Ingredient.create!(name: "cheese", calories: 400)
  @ingredient_2 = Ingredient.create!(name: "chicken", calories: 350)
  @ingredient_3 = Ingredient.create!(name: "lettuce", calories: 50)
  @ingredient_4 = Ingredient.create!(name: "tomato", calories: 90)
  @ingredient_5 = Ingredient.create!(name: "flour", calories: 150)
  @ingredient_6 = Ingredient.create!(name: "oil", calories: 250)
  DishIngredient.create!(dish_id: @dish_1.id, ingredient_id: @ingredient_1.id)
  DishIngredient.create!(dish_id: @dish_1.id, ingredient_id: @ingredient_3.id)
  DishIngredient.create!(dish_id: @dish_1.id, ingredient_id: @ingredient_4.id)
  DishIngredient.create!(dish_id: @dish_2.id, ingredient_id: @ingredient_2.id)
  DishIngredient.create!(dish_id: @dish_3.id, ingredient_id: @ingredient_1.id)
  DishIngredient.create!(dish_id: @dish_3.id, ingredient_id: @ingredient_4.id)
end