# This file was generated by the `rails generate rspec:install` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# The generated `.rspec` file contains `--require spec_helper` which will cause
# this file to always be loaded, without a need to explicitly require it in any
# files.
#
# Given that it is always loaded, you are encouraged to keep this file as
# light-weight as possible. Requiring heavyweight dependencies from this file
# will add to the boot time of your test suite on EVERY test run, even for an
# individual file that may not need all of that loaded. Instead, consider making
# a separate helper file that requires the additional dependencies and performs
# the additional setup, and require it from the spec files that actually need
# it.
#
# See https://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  # rspec-expectations config goes here. You can use an alternate
  # assertion/expectation library such as wrong or the stdlib/minitest
  # assertions if you prefer.
  config.expect_with :rspec do |expectations|
    # This option will default to `true` in RSpec 4. It makes the `description`
    # and `failure_message` of custom matchers include text for helper methods
    # defined using `chain`, e.g.:
    #     be_bigger_than(2).and_smaller_than(4).description
    #     # => "be bigger than 2 and smaller than 4"
    # ...rather than:
    #     # => "be bigger than 2"
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  # rspec-mocks config goes here. You can use an alternate test double
  # library (such as bogus or mocha) by changing the `mock_with` option here.
  config.mock_with :rspec do |mocks|
    # Prevents you from mocking or stubbing a method that does not exist on
    # a real object. This is generally recommended, and will default to
    # `true` in RSpec 4.
    mocks.verify_partial_doubles = true
  end

  # This option will default to `:apply_to_host_groups` in RSpec 4 (and will
  # have no way to turn it off -- the option exists only for backwards
  # compatibility in RSpec 3). It causes shared context metadata to be
  # inherited by the metadata hash of host groups and examples, rather than
  # triggering implicit auto-inclusion in groups with matching metadata.
  config.shared_context_metadata_behavior = :apply_to_host_groups

# The settings below are suggested to provide a good initial experience
# with RSpec, but feel free to customize to your heart's content.
=begin
  # This allows you to limit a spec run to individual examples or groups
  # you care about by tagging them with `:focus` metadata. When nothing
  # is tagged with `:focus`, all examples get run. RSpec also provides
  # aliases for `it`, `describe`, and `context` that include `:focus`
  # metadata: `fit`, `fdescribe` and `fcontext`, respectively.
  config.filter_run_when_matching :focus

  # Allows RSpec to persist some state between runs in order to support
  # the `--only-failures` and `--next-failure` CLI options. We recommend
  # you configure your source control system to ignore this file.
  config.example_status_persistence_file_path = "spec/examples.txt"

  # Limits the available syntax to the non-monkey patched syntax that is
  # recommended. For more details, see:
  # https://rspec.info/features/3-12/rspec-core/configuration/zero-monkey-patching-mode/
  config.disable_monkey_patching!

  # Many RSpec users commonly either run the entire suite or an individual
  # file, and it's useful to allow more verbose output when running an
  # individual spec file.
  if config.files_to_run.one?
    # Use the documentation formatter for detailed output,
    # unless a formatter has already been configured
    # (e.g. via a command-line flag).
    config.default_formatter = "doc"
  end

  # Print the 10 slowest examples and example groups at the
  # end of the spec run, to help surface which specs are running
  # particularly slow.
  config.profile_examples = 10

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = :random

  # Seed global randomization in this process using the `--seed` CLI option.
  # Setting this allows you to use `--seed` to deterministically reproduce
  # test failures related to randomization by passing the same `--seed` value
  # as the one that triggered the failure.
  Kernel.srand config.seed
=end
end

def load_test_data
  @chef_1 = Chef.create!(name:"Billy Bob")
  @chef_2 = Chef.create!(name:"Timmy Bob")
  @dish_1 = @chef_1.dishes.create!(name:"Crawfish etouffee", description: "Its etouffe")
  @dish_2 = @chef_1.dishes.create!(name:"Red Beans and Rice", description: "red beans and rice")
  @dish_3 = @chef_1.dishes.create!(name:"Tacos", description: "they are tacos")
  @dish_4 = @chef_1.dishes.create!(name:"Pizza", description: "its a pizza")
  @dish_5 = @chef_2.dishes.create!(name:"Fried Fish", description: "fried the fish")
  @dish_6 = @chef_2.dishes.create!(name:"Nachos", description: "nachos")
  @dish_7 = @chef_2.dishes.create!(name:"Fried Chicken", description: "fried the chicken")

  @ingredient_1 = @dish_1.ingredients.create!(name:"crawfish", calories: 50)
  @ingredient_2= @dish_1.ingredients.create!(name:"rice", calories: 120)
  @ingredient_3 = @dish_1.ingredients.create!(name:"tomatos", calories: 130)
  @ingredient_4 = @dish_2.ingredients.create!(name:"beans", calories: 200)
  @ingredient_5 = @dish_2.ingredients.create!(name:"rice", calories: 550)
  @ingredient_6 = @dish_2.ingredients.create!(name:"sasuage", calories: 250)
  @ingredient_7 = @dish_3.ingredients.create!(name:"taco shell", calories: 100)
  @ingredient_8 = @dish_3.ingredients.create!(name:"meat", calories: 200)
  @ingredient_9 = @dish_3.ingredients.create!(name:"cheese", calories: 100)
  @ingredient_10 = @dish_4.ingredients.create!(name:"pizza dough", calories: 250)
  @ingredient_11 = @dish_4.ingredients.create!(name:"pizza sauce", calories: 200)
  @ingredient_12 = @dish_4.ingredients.create!(name:"cheese", calories: 150)
  @ingredient_13 = @dish_5.ingredients.create!(name:"fish", calories: 500)
  @ingredient_14 = @dish_5.ingredients.create!(name:"eggs", calories: 500)
  @ingredient_15 = @dish_5.ingredients.create!(name:"fish fry", calories: 100)
  @ingredient_16 = @dish_6.ingredients.create!(name:"chips", calories: 220)
  @ingredient_17 = @dish_6.ingredients.create!(name:"cheese", calories: 220)
  @ingredient_18 = @dish_6.ingredients.create!(name:"salsa", calories: 150)
  @ingredient_19 = @dish_7.ingredients.create!(name:"chicken", calories: 200)
  @ingredient_20 = @dish_7.ingredients.create!(name:"eggs", calories: 100)
  @ingredient_21 = @dish_7.ingredients.create!(name:"chicken batter", calories: 120)
end
